### ISSUE TITLE
timers created inside the poll loop are never triggered

### ISSUE THREAD

**Issue by pusateri** [dimbleby/mio-extras#2]
See carllerche/mio#926 too. Not sure if this is an issue for mio-extras or base mio.

Sample code here:

https://gist.github.com/pusateri/58ea591219ce2a90166daee811c3dbbb

**Comment by dimbleby** [comment]
I'm afraid I'm unlikely to do much with this myself - I mostly forked `mio-extras` to meet my own needs, and this isn't one of them! - but if you do decide that it's a bug in this repository then I'm definitely open to taking a fix.

**Comment by pusateri** [comment]
This turned out to be a problem with the timer being dropped invalidating it.
