### ISSUE TITLE
Timer throws event although timeout has been cancelled

### ISSUE THREAD

**Issue by dasteihn** [dimbleby/mio-extras#3]
This code throws an Event, although the timeout has been cancelled. Why is that? Is this happening on purpose? Or is it a bug?
Sadly I haven't understood the crate extremely well, as the documentation is kind of minimalistic. I created this example based on your tests in the repo.

``` Rust
extern crate mio;
extern crate mio_extras;

use mio::*;
use mio_extras::timer::{Timer, Builder};

use std::time::Duration;


fn main()
{
    const TIMER: Token = Token(2);

    let poll = Poll::new().unwrap();
    let mut gman: Timer<u64> = Default::default();

    poll.register(&gman, TIMER, Ready::readable(), PollOpt::edge()).unwrap();
    let mut gman_tout1; 
    let mut events = Events::with_capacity(1024);
    gman_tout1 = gman.set_timeout(Duration::from_millis(2000), 9001);
    gman.cancel_timeout(&gman_tout1);

    loop {
        poll.poll(&mut events, None).unwrap();

        for event in &events {
            match event.token() {
                TIMER => {
                    println!("Timer-Event!");
                    if gman.poll() == Some(9001) {
                        println!("my timeout occured");
                    }
                },
                _ => println!("awkward"),
            }
        }
    }
}
```

**Comment by dimbleby** [comment]
Bit of background: I rescued this code from the abandoned [`mio-more`](https://github.com/carllerche/mio-more) repository.  So the reality is that I don't actually know it all that well.

Having said that, it's not unusual to get spurious wake-ups from event loops and `poll()` and suchlike; correct usage is - as you have in your code - not to rely on the wakeup but also to check whether the thing *actually* happened.  

That being so I'd say that it's not a bug for "Timer-Event!" to happen (but would be a bug for "My timeout occured" to happen).

My guess is that it's for some reason more efficient - or possibly just easier - not to try and prevent the spurious event.

You're right that the documentation is sparse here.  In my defence I can only say that it was non-existent when I adopted it!  I'd welcome pull requests that improved things.

Does that all make sense?

**Comment by dasteihn** [comment]
No worries, no blame to you. Although I am surprised how it could happen that such an important crate like pollable timers were thrown out of mio in the first place.

Once I have understood the whole lib well enough I am going to provide some examples
