### ISSUE TITLE
Publish new version to crates.io?

### ISSUE THREAD

**Issue by repi** [dimbleby/mio-extras#4]
Would it be possible to publish the latest version as 2.0.6 to crates.io? 

Last published release was a year ago and that still lists only MIT as a supported license in `Cargo.toml` and does include `Apache-2.0` which was to it in mid 2018 in this commit: https://github.com/dimbleby/mio-extras/commit/4d7cd4d2e7a2bcedea0be9172e40a851211c31c1

**Comment by dimbleby** [comment]
Sure, done.

**Comment by repi** [comment]
Thanks, super fast! :)
